"""empty message

Revision ID: 8537dc492180
Revises: a1af5363eb4e
Create Date: 2022-09-17 15:59:27.771130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8537dc492180'
down_revision = 'a1af5363eb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('maintain_weight', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('paleo_diet', sa.Boolean(), nullable=False))
    op.drop_column('user', 'pale_diet')
    op.drop_column('user', 'maintai_weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('maintai_weight', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('pale_diet', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'paleo_diet')
    op.drop_column('user', 'maintain_weight')
    # ### end Alembic commands ###
