"""empty message

Revision ID: a1af5363eb4e
Revises: 7b341695f43f
Create Date: 2022-09-17 15:19:27.146476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1af5363eb4e'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('active_activity', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('female', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('gain_weight', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('gluten_free_diet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('keto_diet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('light_activity', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('lose_weight', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('maintai_weight', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('male', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('moderate_activity', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('norestrictions_diet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('other', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('pale_diet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('pescatarian_diet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('user_age', sa.String(length=2), nullable=False))
    op.add_column('user', sa.Column('user_height_feet', sa.String(length=3), nullable=False))
    op.add_column('user', sa.Column('user_height_inch', sa.String(length=3), nullable=False))
    op.add_column('user', sa.Column('user_weight', sa.String(length=3), nullable=False))
    op.add_column('user', sa.Column('vegan_diet', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('vegeterian_diet', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_height_inch'])
    op.create_unique_constraint(None, 'user', ['user_weight'])
    op.create_unique_constraint(None, 'user', ['user_age'])
    op.create_unique_constraint(None, 'user', ['first_name'])
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['user_height_feet'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'vegeterian_diet')
    op.drop_column('user', 'vegan_diet')
    op.drop_column('user', 'user_weight')
    op.drop_column('user', 'user_height_inch')
    op.drop_column('user', 'user_height_feet')
    op.drop_column('user', 'user_age')
    op.drop_column('user', 'pescatarian_diet')
    op.drop_column('user', 'pale_diet')
    op.drop_column('user', 'other')
    op.drop_column('user', 'norestrictions_diet')
    op.drop_column('user', 'moderate_activity')
    op.drop_column('user', 'male')
    op.drop_column('user', 'maintai_weight')
    op.drop_column('user', 'lose_weight')
    op.drop_column('user', 'light_activity')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'keto_diet')
    op.drop_column('user', 'gluten_free_diet')
    op.drop_column('user', 'gain_weight')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'female')
    op.drop_column('user', 'active_activity')
    op.drop_table('favorite')
    # ### end Alembic commands ###
